Bump React, Gatsby, and regenerate yarn.lock
When attempting to run the website in development, after making no
changes, I was greeted with the following error message:

> The above error occurred in the <StoreStateProvider> component:
>    in StoreStateProvider
>    in App

After some digging, I dsocvered I needed to update React, React DOM, and
Gatsby.

See: https://github.com/gatsbyjs/gatsby/issues/19827

Then after resolving the above issue, I found this error message when
actually viewing the development server:

> Error: React-Hot-Loader: AppContainer should be patched

See: https://github.com/gatsbyjs/gatsby/issues/26979